base_url = "https://contactroberts.com/"
title = "Gabe's Blog"
compile_sass = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"
default_language = "en"

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
author = "Gabe"
