base_url = "https://notthebe.ee/"
title = "Wolfgang's Blog"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "nord", filename = "syntax-theme-dark.css" },
]


[extra]
date_format = "%a %b %e, %Y"
